package(default_visibility = ["//visibility:public"])

exports_files([
    "goog_base.js",
    "named-register.js",
    "soy.min.js",
    "soy_support.js",
    "system.d.ts",
    "system.min.js",
    "tsconfig.json.in",
])
